apiVersion: v1
kind: ServiceAccount
metadata:
  name: dqs-query-status-tracking-service-account
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{  .Values.MSK_ROLE_ARN }}
